import random
a = (random.randint(1,10),random.randint(1,10),random.randint(1,10),random.randint(1,10),random.randint(1,10))
b = min(a)
print(60*"=")
print("Analise do Sorteio de Números".center(60))
print(60*"=")
print("=",end="")
print(f" Os números sorteados foram {a}",end="")
print("=".rjust(21-len(a)))
print("=",end="")
print(f" O menor número é {b}",end="")
print("=".rjust(40))
print("=",end="")
print(f" O maior número é {max(a)}", end="")
print("=".rjust(40))
print(60*"=")